version: '3.8'
services:
  identity_api:
    build: .
    command: 'dotnet Inplanticular.IdentityService.WebAPI.dll --urls=http://*:7001 --environment="Development"'
    restart: unless-stopped
    ports:
      - 7001:7001
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    networks:
      - inplanticular_net
    depends_on:
      - identity_database
      - identity_cache

  identity_database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    networks:
      - inplanticular_net
      
  identity_cache:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    command: redis-server --loglevel warning
    networks:
      - inplanticular_net
    
networks:
  inplanticular_net:
    name: inplanticular_net
    external: true